### ISSUE TITLE
Confusing error message to learners

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#100]
As this [issue](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/70) outlines, learners are getting this confusing error message:
```
Suspicious if-statements below:

line 24 : if (*(ptr+i) >= max){

Expected comparator(s): '==', '!=', '<=', '>=', '>', '<' Expected evaluator(s), if any: '&&', '||'

Examples of expected syntax:

if(resultOfComparison){...} if(variable > 10){...}
```
If you search "suspicious if-statements" in https://github.com/remisharrock/cspace, you can see several quizzes have this if statement regex checker which can be confusing to the learner. Do you have any ideas on how we can change this?

**Comment by mblockelet** [comment]
I'm sorry, it's an issue with your checker and not on our side, so I can't really help with that. You'll probably have to modify the large `if_c` regex variable present in your `checker.py` files to handle that case better.
