### ISSUE TITLE
Space in code freezing Taskgrader

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#102]
In this [issue](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/718) we can see that task grader freezes up on "submission is being evaluated" when this code is inputted into the solution for this [quiz](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020+type@sequential+block@91f8edcd857f410b82baa1860866f4ae/block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020+type@vertical+block@774d7e54673b44ef957688dbf77c0fa7). The answer is correct when put into other solvers just not taskgrader. 
After several trial and error rounds we found that it is a space after the `if(inv==1)` and before the bracket in only this if else statement:
```
if(inv == 1){printf("Invalid tracking code type");}
else{printf("%d bytes", ttlSize);}
```
When that is fixed, the code no more freezes in the solver and runs to show the passed and failed tests. Do we know why this space is throwing off taskgrader? How can it be fixed?

**Comment by AadhyaKocha** [comment]
@mblockelet

**Comment by mblockelet** [comment]
Hello, the issue is in your own checker for that task.

The regexp `if_c` seems to be the issue, as on line 508, the line if `re.match(if_c, line ):` just runs endlessly, causing the issue you get. I cannot help much with checkers when the issue is not obvious, and i don't even know what the regexp does, so you should get in touch with the checker writer to get them to fix the issue.

**Comment by remisharrock** [comment]
we should understand the regex or get rid of it completely; it's used in many taskgraders, do you think we can do a script to autoamtically delete thoses regex and corresponding tests ?  this is linked to https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/703

**Comment by mblockelet** [comment]
Hi @remisharrock , it's possible to write a script or just use an editor to delete those checks each time. Tell me how you'd like to proceed (delete or replace the regexp)!
