### ISSUE TITLE
Taskgrader change not updating in edX

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#103]
I tried updating a task statement in [Taskgrader](https://task-editor.france-ioi.org/#edit/cspace%2F02%20C%20Programming%20Language%20Foundations%2FUnit%202.2%20Arrays%2C%20for%20and%20while%20loops%2F07%20Efficiently%20using%20a%20WHILE%20loop%2F01_controlling%20an%20epidemic) to update an edX quiz. Weirdly, I was able to push the new code and update it on Cspace but when I press save and import in Taskgrader and it goes to the Task Importer tab, I get the error that there is no index.html found. This also does not let the edX quiz get updated.
![Screenshot 2022-01-20 at 4 39 33 PM](https://user-images.githubusercontent.com/51734801/150427038-94287307-b7bc-4e47-9878-901acd758a2d.png)
However, in Task Manager the index.html is still there. It is also weird because I don't think it should be trying an SVN checkout. This issue is also not task specific but is occurring for all the quizzes on TaskGrader.

**Comment by mblockelet** [comment]
Hi,

I can confirm the issue. A workaround for now is to click on "Display full interface", then "Use normal username / password authentication", then use github credentials (username + a token from https://github.com/settings/tokens).

I'm very busy right now so I don't have time to look into it right now, but I'll try to find some time in the next few days.

**Comment by AadhyaKocha** [comment]
hi @mblockelet 
No worries about fixing it in a few days. Can I ask where the option is for "Display Full Interface"? I couldn't find it on Taskgrader or on edX studio or live version.

**Comment by mblockelet** [comment]
Hello,

Sorry for the delay, I hadn't seen your message and forgot about the issue. I fixed it now, so it should work directly.

About the workaround, I just realized from your screenshot that the button "Display Full Interface" isn't displayed when the top navbar is over two lines, as the second line covers the button. Note that the embedded frame is https://svnimport.france-ioi.org/, so in case of issue you can access it through there (however you need to enter all the information of course).
