### ISSUE TITLE
task editor quiz creation

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#106]
I am trying to recreate this [edx course](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020+type@sequential+block@95d482037cf4460db37858d10616e1b0/block-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020+type@vertical+block@da9d60abcf544636b3418def7147eabc](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearning.edx.org%2Fcourse%2Fcourse-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B1T2020%2Fblock-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B1T2020%2Btype%40sequential%2Bblock%4095d482037cf4460db37858d10616e1b0%2Fblock-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B1T2020%2Btype%40vertical%2Bblock%40da9d60abcf544636b3418def7147eabc&data=04%7C01%7CAadhya.N.Kocha.22%40dartmouth.edu%7C4c692bbe0ae54699286c08da171c40e3%7C995b093648d640e5a31ebf689ec9446f%7C0%7C0%7C637847707370484605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8AcHdXHN12fivSzr8BTxyFt71XgV%2FNiEtCueIXCqCVc%3D&reserved=0 ) on taskEditor [here](https://task-editor.france-ioi.org/#edit/cspace%2F05%20C%20Programming%20Advanced%20Data%20Types%2FUnit%205.3%20Linked%20lists%2F02%20Linking%20nodes%2F02_createStudent%20need%20help ). However, when I am testing the task, I am told to try again after a few minutes but has not worked in several days now.
<img width="1181" alt="Screenshot 2022-04-14 at 8 31 12 AM" src="https://user-images.githubusercontent.com/51734801/163391105-86ff6a29-5194-46a5-bb53-72b5a905363a.png">
Is there a setting I have done incorrectly that prevents me from testing it? 
Also I want to figure out  how that "show answer" option shows only when the student chooses option B and not for both options. Is there a setting in task editor that allows me to specify that and give a conditional answer?

**Comment by mblockelet** [comment]
Hi @AadhyaKocha,

In the "Quizz settings", you need to set the "Server side grader URL". I added it on that task for you, but please don't forget to add it on other tasks. The task now works without issue.

Cheers,
