### ISSUE TITLE
Quiz for getting code - Grading issue

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#112]
We are still trying to recreate this [edX course](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020+type@sequential+block@95d482037cf4460db37858d10616e1b0/block-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020+type@vertical+block@da9d60abcf544636b3418def7147eabc) on taskEditor [here](https://task-editor.france-ioi.org/#edit/cspace%2F05%20C%20Programming%20Advanced%20Data%20Types%2FUnit%205.3%20Linked%20lists%2F02%20Linking%20nodes%2F02_createStudent%20need%20help). When integrated into Coursera this is the issue as Catherine explained: "The quizzes work perfectly when I type in "yes" as my answer ... I don't receive the solution and I get 100% on the quiz before continuing on to the coding section. When I type in "no," it gives me the necessary code and 0% on the quiz, as expected. However, it continues to show up on my "grades" as being incomplete and that the course is unfinished (as compared to course complete without a perfect score). Then, I returned to the quiz after having closed the window, it allows me to re-enter text, where I can type in "yes" and get full credit, despite having not passed the question earlier."
So 2 issues:
- The student can reopen the LTI link once closed and re-enter the answer to change their grade
- And second that if left at no the student cannot get their entire course as completed yet

A few questions for @mblockelet then:
1. Could it be the case that an activity in Coursera is either “passed” or “incomplete” (so students cannot fail or get a zero to finish the course). Or is there a functionality we can do in Taskgrader to give a score zero but mark the quiz as complete and not allow the user to reopen the LTI link? 
2. If nothing else, is it possible to change the scoring to be to give 1 point for asking for the hint and 2 points for NOT asking for the hint and setting the passing threshold at 1 point?
3. Any other solutions to this problem you recommend?

**Comment by mblockelet** [comment]
Hi @AadhyaKocha, the problem with being able to change the answer is solved. Now quizzes will restore the last state properly, and hence not allow to answer again. (Note that this won't apply to old answers, it will only work after on new submissions onwards.)

Please tell me if everything is fine.

**Comment by EllaHa** [comment]
We can close this issue. Thanks for the help Michel!
