### ISSUE TITLE
Answers option visual

### ISSUE THREAD

**Issue by catherinechoww** [France-ioi/taskgrader#114]
Hello Michel - I am reaching out for assistance with the visual aesthetics of a multiple choice quiz. See the following image, where for question 3, option A's button is smaller than option B and C.

![image](https://user-images.githubusercontent.com/98115742/232588469-d022943c-4739-4b2b-849b-79ec5eeab370.png)

The quiz can also be seen in Coursera's platform through this link:
[https://www.coursera.org/learn/c-programming-advanced-data-types/gradedLti/NTVWj/get-to-know-the-concept-of-a-linked-list](url)

The quiz itself can be found in Task Editor through this link:
[https://task-editor.france-ioi.org/#edit/cspace%2F05%20C%20Programming%20Advanced%20Data%20Types%2FUnit%205.2%20Structures%20and%20pointers%2F03%20Get%20to%20know%20the%20concept%20of%20a%20linked%20list%2F05_manipulate%20linked%20lists](url)

Would you please be able to provide documentation on how I can fix this? Thank you!

**Comment by catherinechoww** [comment]
@mblockelet

Would you be able to assist me with this?

**Comment by mblockelet** [comment]
Hello, the issue should now be fixed without needing any modification on your side. It might not display to you instantly depending on when your cache will be refreshed.

**Comment by catherinechoww** [comment]
That looks wonderful! Thank you so much, @mblockelet, for your help!
