### ISSUE TITLE
new design of taskgrader: a new menu appears and should not appear

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#117]
it looks like the coursera template has been changed and now a new menu appears on top of a task and enables the navigation through all the activities and that should not happen. 
Also there is a new "history" tab that is new, it was not there before (what is the difference between this new history tab and the "clock" button on the code editor that also shows an history ?)
example here
 
![Capture d’écran du 2023-07-27 17-14-43](https://github.com/France-ioi/taskgrader/assets/8048877/cac890d8-6c50-4c4f-a6e6-d1931c285344)

and here it was like that before:
![image](https://github.com/France-ioi/taskgrader/assets/8048877/7a003729-898a-4406-8e09-33fb90ccf78d)

**Comment by mblockelet** [comment]
Salut, c'est corrigé pour l'historique. On voit pour corriger la navigation aussi.

**Comment by remisharrock** [comment]
salut Michel, je viens de voir que la barre en plus haute qu'avant et sur les codecast ça tronque la vue cf https://github.com/France-ioi/codecast/issues/339  
ça fait 3 semaines a priori que c'est comme ça, pourrais-tu voir merci

**Comment by mblockelet** [comment]
Salut, tous les points sont corrigés maintenant.
