### ISSUE TITLE
MOOC 7 - "Invalid memory access"

### ISSUE THREAD

**Issue by catherinechoww** [France-ioi/taskgrader#118]
Hi @mblockelet,

There seems to be a problem with the last activity of MOOC 7 called "write numbers to a file". Users are reporting that they're getting the issue shown below. When I tested the correct answer from Task Editor itself, I got the same error. It says:

![image](https://github.com/France-ioi/taskgrader/assets/98115742/05aa9c53-3190-43fd-8a91-994fb91d9f94)

The correct answer I used once allowed me to get 100% so it's odd that it's not working now. Here are some links:
Assignment on Coursera: [https://telecom-paris.france-ioi.org/en/a/5484359769606683346;p=4702,458602124916982205,7683322731625411756,2405403127530483676,100883173480640452;pa=0](url)
Task editor: [https://task-editor.france-ioi.org/#edit/cspace%2F07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries%2FUnit%207.3%20File%20operations%20in%20C%2F04%20Writing%20to%20a%20file%2F01_write%20numbers%20to%20a%20file](url)
Assignment on edX: [https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@sequential+block@da94b90a903d4495bb0f1d0ffff513b0/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@vertical+block@bc6cf683f6664bb197858ac80fbefbf8https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@sequential+block@da94b90a903d4495bb0f1d0ffff513b0/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@vertical+block@bc6cf683f6664bb197858ac80fbefbf8](url)

Do you have any tips on how I might fix this?

**Comment by EllaHa** [comment]
this issue is linked with https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/786

**Comment by mblockelet** [comment]
Hi @EllaHa , it seems the file "myGrades.txt" is missing from the repository. Oddly enough, I can find history for the file : https://github.com/remisharrock/cspace/commits/a7b185ca76265b8cdfd40750db794ea8c850a8bc/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.3%20File%20operations%20in%20C/04%20Writing%20to%20a%20file/01_write%20numbers%20to%20a%20file/tests/gen/myGrades.txt

but I couldn't find any commit deleting it. Either way the file will need to be recreated so the task can work properly again.

**Comment by catherinechoww** [comment]
Thank you for your help @mblockelet ! We were able to add the file back and now the task is working.
