### ISSUE TITLE
hasUserTests: true n'affiche pas les entrées/sorties dans la soumission

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#12]
voici un exemple:
https://tasks.algorea.org/?taskId=979236209381147136
ou LTI https://lti.algorea.org/?taskUrl=https%3A%2F%2Ftasks.algorea.org%2Ftask.html%3FtaskId%3D979236209381147136 
(correspond à Telecom/MOOC1/Week2/taskTemplate )

**Comment by eroux** [comment]
corrigé, merci !

**Comment by eroux** [comment]
P.S.: il faut mettre hasUserTests dans les metadata, j'ai corrigé sur le svn

**Comment by remisharrock** [comment]
ha ok je vois le changement super merci

**Comment by remisharrock** [comment]
du coup il faut mettre hasUserTests: true  dans
PEMTaskMetaData
ou dans 
FIOITaskMetaData
?
car dans ta solution tu le déplaces de FIOITaskMetaData vers PEMTaskMetaData  mais dans les commentaires de FIOITaskMetaData  il y a bien marqué // can user build tests?  ;  pas dans PEMTaskMetaData  ?

**Comment by eroux** [comment]
on peut déplacer le commentaire aussi oui, tout va dans PEMTaskMetaData

**Comment by remisharrock** [comment]
ça a été changé car  ce n'était pas comme cela avant ?
