### ISSUE TITLE
grader_data.js 404 not found

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#122]
J'ai des retours sur le MOOC sur Coursera pendant les quiz d'un 404 sur grader_data.js 

voici l'issue: https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/794

A learner has been taking the quiz and scoring 100/100, but it does not update on their profile and continues to show as incomplete.

https://www.coursera.org/learn/linux-basics-the-command-line-interface/discussions/forums/3EsZCrmUEeyBoBL7F1DbTw/threads/IoDzeDcSEe-eFgr_9lJ0ZQ

merci pour l'aide !

![image](https://github.com/user-attachments/assets/517172ff-ffd7-48d5-a4b1-4557cb9bba69)

**Comment by mblockelet** [comment]
Bonjour Rémi, j'ai répondu sur le bugreport ci-dessus ; comme a priori il n'y a pas de problème de notre côté, je ferme cette issue!
