### ISSUE TITLE
sur fun-mooc bouton valider la réponse grisé lors d'une réponse fausse

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#14]
Sur fun-mooc.fr , le bouton valider la réponse est toujours grisé lorsqu'une réponse est fausse ; il devrait se dégriser.
La console javascript affiche:
task-xd-pr.js:103 platform.validate with mode done(anonymous function) @ task-xd-pr.js:103onMessage @ jschannel.js:423s_onMessage @ jschannel.js:187
task-xd-pr.js:258 [0, "test message", "eyJhbGciOiJSUzUxMiJ9.eyJpZFVzZXIiOiIzNjM2ODMiLCJpZ…kjMSQB1hVcSrKia3Uzs3HL8WrqI2R3Gt_72IT3lcJUjGvqrsw"]newSuccess @ task-xd-pr.js:258onMessage @ jschannel.js:493s_onMessage @ jschannel.js:195
platform-pr.js:179 [Object, "parsererror"]0: Object1: "parsererror"callee: (...)get callee: ThrowTypeError()set callee: ThrowTypeError()caller: (...)get caller: ThrowTypeError()set caller: ThrowTypeError()length: 2Symbol(Symbol.iterator): values()__proto__: Objecterror @ platform-pr.js:179onMessage @ jschannel.js:488s_onMessage @ jschannel.js:195
2taskController.js:253 editors data equal to previously saved, not saving

**Comment by mblockelet** [comment]
Salut ! Le problème a été réglé, c'était une erreur de droits sur le serveur d'exercices.
Merci !
