### ISSUE TITLE
bouton tout sauvegarder disparu ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#15]
sur fun-mooc.fr  le bouton tout sauvegarder a disparu .
J'ai un tutoriel vidéo qui montre ce bouton disparu : https://d3gzh2mxagd143.cloudfront.net/videos/zFKsysPezGAN/HD.mp4

**Comment by mblockelet** [comment]
Le bouton "tout sauvegarder" a été enlevé parce que [TaskPlatform](/France-ioi/TaskPlatform) sauvegarde maintenant automatiquement le code quand il est modifié. Est-ce que cela pose problème qu'il ne soit plus là ?

**Comment by remisharrock** [comment]
ha d'accord, donc c'est à chaque frappe de touche ? :-)

**Comment by mblockelet** [comment]
Non, c'est quelque chose comme chaque seconde si le code a été modifié :)

**Comment by remisharrock** [comment]
ok
