### ISSUE TITLE
bug grader par défaut ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#18]
voici un bug en vidéo:
https://youtu.be/jYNz4uQDDmg

**Comment by mblockelet** [comment]
Le bug est lié à https://lists.gnu.org/archive/html/bug-diffutils/2015-06/msg00003.html :

`diff -B` ignorait le dernier caractère si le fichier se terminait sans retour à la ligne.

a39738e corrige cela. Merci beaucoup pour le rapport de bug !

**Comment by mathias-hiron** [comment]
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20929

Le bug a été corrigé dans la nouvelle version de diffutils. Ce qui est
amusant c'est que je connais personnellement celui qui a remonté le bug à
l'origine, c'est mon homologue au Brésil :)

**Comment by remisharrock** [comment]
haha le monde est petit !
