### ISSUE TITLE
sur fun soumission en cours d'évaluation ne s'arrête pas ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#19]
bonjour, j'ai lancé mon MOOC programmer en C aujourd'hui.
Il y a un exo avec taskgrader et j'ai cette erreur : 
: tasks.algorea.org/bower_components/fioi-editor2/dist/fioi-editor2.min.js:6 WARNING: Tried to load angular more than once.
taskController.js:253 editors data equal to previously saved, not saving
task-xd-pr.js:103 platform.validate with mode done(anonymous function) @ task-xd-pr.js:103
taskController.js:253 editors data equal to previously saved, not saving
platform-pr.js:179 ["timeout_error", "timeout (30000ms) exceeded on method 'tasks.algorea.org::task.gradeAnswer'"]error @ platform-pr.js:179onMessage @ jschannel.js:488s_onMessage @ jschannel.js:195
taskController.js:253 editors data equal to previously saved, not saving

**Comment by remisharrock** [comment]
j'ai essayé sur chrome et firefox, même problème

**Comment by eroux** [comment]
Bonjour Rémi, comment est-ce que je peux tester ? Merci

**Comment by remisharrock** [comment]
a priori c'est réparé, merci
