### ISSUE TITLE
import svn algorea

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#21]
juste pour savoir si le format a changé pour algorea car je testais parfois après avoir importé sur svn avec le lien Url pour la plateforme Algoréa :  qui n'a plus l'air de fonctionner ? 
par exemple https://tasks.algorea.org/?taskId=865083096916841984

**Comment by mblockelet** [comment]
Salut,

Il n'est plus possible de tester les tâches sans token. L'interface d'import SVN donne un token de test (valide ~2 jours) à chaque import, sous le lien "Tester la tâche"; s'il y a juste besoin de regénérer un token, il suffit de cocher la case "ne pas réimporter".

**Comment by remisharrock** [comment]
OK !
