### ISSUE TITLE
scanf avec un test input qui n'a pas de saut de ligne à la fin sur FUN pour le MOOC ABC du langage C

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#22]
Salut, sur FUN, MOOC ABC du langage C, semaine 3, activité répartition du poids 
(sur taskgrader Telecom MOOC1 WEEK3 taskpoids)
quelqu'un a un problème avec le test3 (les autres tests passent):

```
#include <stdio.h>

int main(){
    int nbDeWagon;
    double poidsWagon;
    double poidsTotal = 0;
    scanf("%d", &nbDeWagon);
    if(nbDeWagon > 50){
        nbDeWagon = 50;
    }
    double tabWagon[nbDeWagon];
    for(int index = 0; index < nbDeWagon ; index++){
        scanf("%lf", &poidsWagon);
        tabWagon[index] = poidsWagon;
        poidsTotal += poidsWagon;
    }
    poidsTotal /= (double)nbDeWagon;
    for(int index = 0; index < nbDeWagon ; index++){
        printf("%.1lf\n", ( poidsTotal - tabWagon[index]));    
    }
    return 0;
}
```
effectivement pour le test3.in il n'y a pas de retour de ligne à la fin.
Pourquoi cela a un impact ? 
C'est d'autant plus intriguant qu'en changeant par
```
     scanf("%lf", &tabWagon[index]);
        poidsTotal +=  tabWagon[index];
```
ça fonctionne ... 
vous avez une idée ?

**Comment by mblockelet** [comment]
Salut,

J'ai l'impression que le problème ne vient pas (entièrement) du retour à la ligne, mais du fait que test3.in dit sur la première ligne qu'il y a 7 wagons, puis ne donne que 6 valeurs.

Du coup, en fonction du code réalisé, on a des résultats différents :

* si on passe par poidsWagon, du coup poidsWagon garde sa valeur (scanf semble ne pas y toucher vu qu'il n'y a plus rien), et on ajoute poidsWagon encore une fois
* si on passe directement par tabWagon[index], tabWagon[6] (le dernier, celui correspondant à la valeur qui n'existe pas) vaudra 0

ce qui du coup donne deux résultats différents, le deuxième correspondant à la "réponse acceptée" juste parce que c'est la même chose que la solution de référence.

Bref, il faudrait corriger le nombre de wagons au début de test3.in et ça devrait être bon !

**Comment by remisharrock** [comment]
Génial ! oui ça doit être cela !
Michel, ça te dérangerait de changer avec 6 puis de déployer ? J'ai pas l'ordi qu'il faut pour le faire sous la main.
Merci beaucoup !!

**Comment by mblockelet** [comment]
C'est bon, j'ai déployé ! Maintenant les deux versions du code passent sans problème sur le test 3.
A bientôt !
