### ISSUE TITLE
Suppression des lignes vides dans les rapports d'erreurs

### ISSUE THREAD

**Issue by pacalet** [France-ioi/taskgrader#23]
Lorsque la sortie produite par un code testé comporte des lignes vides, elles sont filtrées dans l'éventuel rapport d'erreur, ce qui prive parfois les apprenants d'informations utiles pour comprendre leurs erreurs. Voir un [exemple de ce genre de situation](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/discussion/forum/d8d7d5870fb27762b4294426ae75a5bd5d6dceb4/threads/58bfe2e9a0241e7a7c004e30) dans le MOOC [ABC du langage C](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/about).

**Comment by epixode** [comment]
Je ne comprends pas, pouvez-vous donner un exemple ?

**Comment by mblockelet** [comment]
Bonjour !

En effet, le checker *par défaut* (qui est utilisé pour le sujet en question) ignore les lignes vides pour comparer la solution à celle attendue. Pour les sujets où les lignes vides sont importantes, il faut soit donner des options au checker par défaut pour désactiver ce comportement, soit utiliser un checker spécial qui fera un message d'évaluation correspondant mieux à ce qui est attendu.

On a prévu d'offrir un moyen aux utilisateurs de pouvoir voir la sortie de leur solution lorsque l'auteur du sujet le leur permet, mais ce n'est pas une priorité actuellement.

Par ailleurs, il faut que les étudiants fassent attention lorsqu'ils utilisent le taskgrader pour tester des programmes qui ne répondent pas au sujet courant, vu que selon les paramètres du sujet ça peut affecter le retour qu'ils obtiennent. Le système "Essayer sur le test courant" est fait pour tester des solutions au sujet courant.

A bientôt !
