### ISSUE TITLE
Effet des caractères de code ASCII > 127

### ISSUE THREAD

**Issue by pacalet** [France-ioi/taskgrader#24]
Dans le MOOC [ABC du langage C](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/about) un apprenant a, pour des raisons qui seraient trop longues à expliquer, envoyé sur la sortie standard le caractère de code ASCII 224. Le résultat a été qu'au lieu de lui montrer les différences entre la sortie produite et la sortie attendue, le taskgrader a répondu :

> Il n'existe pas de tests pour ce problème

Pour en savoir plus, voir la [discussion du forum](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/discussion/forum/b7745c71868095f85e6743b61982e6bdff1f29fd/threads/58c68e90a0241e069e0052f3#) à ce sujet.

Dernière minute : d'autres ont rencontré cet étrange message sur d'autres exercices. Voir [ici](https://www.fun-mooc.fr/courses/MinesTelecom/04019S02/session02/discussion/forum/i4x-MinesTelecom-04019S02-course-session02/threads/58c55081a0241eab2c005255), par exemple.

**Comment by mblockelet** [comment]
Bonjour,

Merci beaucoup pour le rapport de bug. Je suis assez surpris qu'on ne soit pas tombés dessus jusqu'ici...

Il s'agissait en effet d'un problème lorsqu'une solution envoyait des caractères qui étaient invalides en UTF-8 sur sa sortie; il est maintenant corrigé et en production. J'ai testé une solution qui posait problème, maintenant il n'y a plus de problème et on obtient bien le résultat de l'évaluation.

Bonne journée !

**Comment by pacalet** [comment]
> Je suis assez surpris qu'on ne soit pas tombés dessus jusqu'ici

En effet, vu le bombardement de codes exotiques que le taskgrader voit passer, c'est assez bluffant que ça n'ait pas été relevé jusqu'ici. Content de savoir que vous avez résolu le problème. Bravo pour la réactivité.
