### ISSUE TITLE
Résidu de français dans l'interface anglaise

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#27]
Bonjour, 

Attention les textes liées à l'apparition des "Hints" sont encore visibles en français. 
![image](https://user-images.githubusercontent.com/19490273/32629563-f180a626-c599-11e7-9359-692cce019244.png)

Merci pour ces corrections,

**Comment by EllaHa** [comment]
de même pour le bouton (avant d'obtenir le conseil) 
![image](https://user-images.githubusercontent.com/19490273/32753433-1c194ca4-c8cd-11e7-8227-cb1ee9949745.png)

**Comment by Frigory33** [comment]
En plus, en français, il faudrait écrire « quelque part » sans trait d’union, et mettre une espace avant le deux-points après « Conseil 1 ».

**Comment by mblockelet** [comment]
Merci d'avoir signalé, c'est corrigé aussi !
