### ISSUE TITLE
Résidus de français dans l'interface anglaise

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#28]
![image](https://user-images.githubusercontent.com/19490273/32753461-35b86d3e-c8cd-11e7-8417-af17a94ded4e.png)

Attention, lorsque l'on souhaite afficher l'historique des soumissions sur le taskgrader version anglaise, le texte apparait en français.

**Comment by mblockelet** [comment]
C'est corrigé, merci de l'avoir signalé !
