### ISSUE TITLE
faire apparaitre la date selon le format américain sur les soumissions de la version anglaise

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#29]
Attention lorsque l'on soumet un code sur le taskgrader version anglaise, le format de la date obtenue n'est pas au format américain. Serait-il possible d'afficher MM-DD-YY ?
![image](https://user-images.githubusercontent.com/19490273/32753558-9a0537c2-c8cd-11e7-9195-667463af7f40.png)

**Comment by mblockelet** [comment]
Bonjour,
Pour ce faire, il faut mettre, dans le lien LTI, sLocale à en_us, c'est-à-dire "sLocale=en_us" au lieu de "sLocale=en", vu que la locale en correspond par défaut à l'anglais du Royaume-Uni.
Je vais bientôt ajouter une option dans svnimport pour générer directement des liens LTI avec ces options.
