### ISSUE TITLE
permission denied error

### ISSUE THREAD

**Issue by eroux** [France-ioi/taskgrader#3]
Testing with FranceIOI tasks, I get:

    $ ./_common/genJson/genJson.py FranceIOI/Contests/2014/Algorea_preselection1/3_spaceship/
    * Generating defaultParams for FranceIOI/Contests/2014/Algorea_preselection1/3_spaceship/
    gen.sh detected
    Dependencies found for generator: gen.sh, generators.py, libRobot.py, generator.py, sol-ismael-naiv.jvs, sol-ismael-naiv.c, sol-ismael-naiv.py, sol-ismael-naiv.java, sol-ismael-naiv.cpp
    sanitizer.cpp detected
    check.cpp detected

    * Output from auto-test with taskgrader
    Cannot write /sys/fs/cgroup/memory/box-50/tasks: No such file or directory
    Traceback (most recent call last):
      File "/home/eroux/Drupchen/taskgrader/taskgrader.py", line 790, in <module>
        json.dump(evaluation(inJson), sys.stdout)
      File "/home/eroux/Drupchen/taskgrader/taskgrader.py", line 644, in evaluation
        getCacheDir(generatorsFiles[gen['idGenerator']], 'e-generator'), outputFiles=['*.in', '*.out', '*.h', '*.java', '*.ml', '*.mli', '*.pas', '*.py'])
      File "/home/eroux/Drupchen/taskgrader/taskgrader.py", line 399, in cachedExecute
        report = execute(executionParams, cmdLine, workingDir, stdinFile=stdinFile, stdoutFile=stdoutFile, language=language)
      File "/home/eroux/Drupchen/taskgrader/taskgrader.py", line 313, in execute
        filecopy(isolateDir + 'isolated.stdout', stdoutFile)
      File "/home/eroux/Drupchen/taskgrader/taskgrader.py", line 84, in filecopy
        shutil.copy(filefrom, fileto)
      File "/usr/lib/python2.7/shutil.py", line 119, in copy
        copyfile(src, dst)
      File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 13] Permission denied: '/tmp/box/50/box/isolated.stdout'

and indeed /tmp/box is not writeable by my user:

    $ ls -l /tmp/
    drwxr-xr-x 3 root     eroux      4096 août   5 09:41 box

**Comment by mblockelet** [comment]
C'est parce que le filesystem des control groups n'est pas monté; désolé, je n'ai pas encore mis à jour la documentation par rapport à ça, je vais le faire; peut-être il faudrait aussi essayer d'avoir une détection automatique de s'il est monté ou pas, je ne sais pas...

**Comment by mblockelet** [comment]
En attendant tu peux les désactiver dans la config, ça n'est pas très grave de ne pas les utiliser hors d'un contexte où la mémoire utilisée n'est pas hyper importante...

**Comment by eroux** [comment]
Ah super merci ça marche !

**Comment by eroux** [comment]
Autre bug : j'ai quelques milliers (peut-être dizaine de milliers) de

    /bin/chmod: modification des droits de « /tmp/box/25/root/proc/sysvipc/sem »: Système de fichiers accessible en lecture seulement

(pour tous les fichiers de /proc, etc.)

puis

    Cannot rmdir /tmp/box/25: Directory not empty

Tu sais d'où ça peut venir ?

**Comment by mblockelet** [comment]
C'est bizarre, je n'ai jamais eu ça. À vue d'oeil, il doit y avoir un problème avec isolate qui ne unmount pas après son exécution, du coup il reste les bind qu'il a créés. Je n'ai pas d'idée de ce qui est à l'origine de ça, aurais-tu plus d'informations sur ce qu'il se passe avant ou sur une façon de reproduire ?

PS : est-ce que ce ne serait pas des relicats de isolate qui plantait quand les cgroups étaient activés ?

**Comment by eroux** [comment]
hmpf... j'ai un peu naïvement fait `rm -rf /tmp/box` puis un `ctrl+c` pas trop tard... j'espère ne pas en avoir pour quelques jours avant de pouvoir rebosser...

**Comment by eroux** [comment]
Bon, je crois que je suis bon pour réinstaller mon serveur (plus de `sudo` et pas de mdp root)... j'ai des dumps mysql pas trop vieux heureusement... Ce serait bien je pense de monter les fichiers dans `/mnt` ou `/media`, pour éviter les problèmes. Je pense qu'il y a quelques améliorations possibles concernant la sécurité...

**Comment by mblockelet** [comment]
Désolé pour toi... Le problème, c'est que `/tmp/box` est hardcodé dans isolate (à ce que je sache), donc il faudrait probablement le modifier pour qu'il utilise un dossier plus sûr que `/tmp`; je vais voir pour faire que le taskgrader détecte mieux quand isolate plante et essaie de nettoyer avant de rendre la main.

**Comment by eroux** [comment]
ce serait pas mal oui, et bugreporter à isolate aussi, je pense qu'ils peuvent comprendre...

**Comment by eroux** [comment]
Je me demande si ce n'est pas la même erreur que #6, ça bug au même endroit, la différence est que dans #6 j'ai monté les cgroups.

**Comment by eroux** [comment]
fixed by bf6a56925a68c45f22721822b0f05a36f8660883
