### ISSUE TITLE
New lines within <pre> tags not showing

### ISSUE THREAD

**Issue by petraBT** [France-ioi/taskgrader#31]
For an example, please see Telecom/MOOC1/Week2/taskPyramide . The pyramid within <pre> tags is showing up "flattened" - without line breaks. Thank you!

**Comment by mblockelet** [comment]
Hi,

When I import the task, it looks fine to me. However, I just fixed seemingly unrelated issues linked to the task import. Could you try importing the task again and telling me if the issue is still there, which could mean maybe browser-related issues?

Thanks!

**Comment by petraBT** [comment]
Oh wow- it’s working just fine now! Thank you!

—Petra

On Dec 7, 2017, at 1:33 PM, mblockelet <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

When I import the task, it looks fine to me. However, I just fixed seemingly unrelated issues linked to the task import. Could you try importing the task again and telling me if the issue is still there, which could mean maybe browser-related issues?

Thanks!
