### ISSUE TITLE
feedback avec le</pre> qui apparaît

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#33]
Dans le MOOC 1 "ABC du langage C", troisième semaine, les fonctions, activité convertisseur intelligent
avec ce code étudiant soumis (pas très correct) on a une sortie intéressante qui affiche </pre>:

![image](https://user-images.githubusercontent.com/8048877/38023389-79151f9a-3282-11e8-862a-3b880ae7e6dc.png)

```
#include <stdio.h>

int main(){
   int nbval;
   scanf("%d", &nbval);
   double val1 = 0;
   double val2 = 0;
   char unit[10];
   for(int i=0; i<nbval; i++){
       scanf("%lf", &val1);
       scanf("%s", unit);
       if(unit[0]== 'm'){
           val2 = val1/(0.3048);
           unit[0] = 'p';
           printf("%lf %s", val2, unit);
       }
       if(unit[0] == 'g'){
           val2 = val1*(0.002205);
           unit[0] = 'l';
           printf("%lf %s", val2, unit);
       }
       if(unit[0] == 'c'){
           val2 = 32 + ((1.8)*val1);
           unit[0] = 'f';
           printf("%lf %s", val2, unit);
       }
       printf("\n");
   }

   return 0;
}
```

**Comment by mblockelet** [comment]
Le fichier `test1.in` de la tâche était le fautif : il incluait le </pre> et puis des lignes "sortie: [etc.]" pour une raison inconnue. J'ai commité une version corrigée de `test1.in`, c'est bon maintenant.

Bizarrement, d'après l'historique du SVN le fichier n'a pas été modifié depuis le 01/07/2016...

**Comment by remisharrock** [comment]
merci!
