### ISSUE TITLE
Taskgrader loading in more than 2 seconds

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#37]
Hi Michel, 
I am located in Argentina and it takes a while for me to load the tasgrader [on the edX interface]([url](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/67a918138c7b4b358ebc25979b80a1d1/?child=first)). 

I first get this 
![image](https://user-images.githubusercontent.com/19490273/39592998-f2afb414-4ede-11e8-9070-73a8ef6bce65.png)
And something interesting, while the task is loading I can see this, 
![image](https://user-images.githubusercontent.com/19490273/39592898-9dd0c94c-4ede-11e8-8d8c-6392afc20d2b.png)
before it looks the correct way, 
![image](https://user-images.githubusercontent.com/19490273/39593058-2279b30c-4edf-11e8-8b1b-a871e99de4f5.png)
would this be because the theme is loading slow?
Can we do something about this because it is kind of confusing to have different views of the interface appearing?

**Comment by mblockelet** [comment]
Hi, it will now display a loading animation until the task and source codes are loaded, which should reduce confusion.
