### ISSUE TITLE
LTI intergration with scolling : tabs stay on the top

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#39]
Is it possible to have the tabs staying on the top when integrating with LTI on edx?

![image](https://user-images.githubusercontent.com/8048877/39877678-d6cc981e-5476-11e8-941b-e2c9ffdb8d0f.png)

**Comment by remisharrock** [comment]
it's a scroling issue, edx has fixed height... so if it possible to add a javascript to "pin to the top" the tabs that would be awesome

**Comment by EllaHa** [comment]
Hi Michel, any update on the fact this would be possible? Thanks

**Comment by mblockelet** [comment]
Hi, it should be possible, but I didn't have time to try it yet. I should have time to take care of that by this week-end!

**Comment by EllaHa** [comment]
Thanks Michel !

**Comment by mblockelet** [comment]
Hi, the theme has been modified to keep the tabs at the top!

**Comment by remisharrock** [comment]
Hello, it looks like it doesn't work anymore?

**Comment by mblockelet** [comment]
Hi, I had to revert in an emergency yesterday evening as, according to #41, it made the tabs disappear completely on Safari, which makes the tasks unable to complete on. I'm still trying to get a hold of a recent version of Safari (my Macbook doesn't want to update anymore, and its Safari version is so old it somehow manages to be unable to connect to some HTTPS websites). I hope to have it fixed back very very soon...

**Comment by remisharrock** [comment]
Nice, thank you !
