### ISSUE TITLE
scrollbars sur FUN-MOOC

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#40]
voir la vidéo
https://www.youtube.com/watch?v=1YJ5iQpzZZM

**Comment by mblockelet** [comment]
C'est corrigé, c'était une conséquence des modifications sur les onglets. Le layout que j'avais fait faisait 799px de hauteur sur mon navigateur, mais je suppose que ces 799px peuvent parfois être 801px sur certains navigateurs; du coup j'ai fait en sorte qu'il y ait une marge plus importante (ça fait 785px sur mon navigateur maintenant).
