### ISSUE TITLE
Wording changes

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#42]
Translations - corrections say “Evaluation Answered:”
Validate answer should be "submit"
![image](https://user-images.githubusercontent.com/19490273/41107768-60d9c170-6a49-11e8-85da-f59b3c4573da.png)

Indicate that expected output has punctuation/case removed
"Ask a hint" should be "Request a hint"
"Congratulations, your program validated this test." should be "... passed this test"
"Validated test" should be "Test passed"

![image](https://user-images.githubusercontent.com/19490273/41107872-99107a7a-6a49-11e8-8c3d-3d19e424fcb7.png)

**Comment by mblockelet** [comment]
Hi,
> corrections say “Evaluation Answered:”

Do you think a title such as "Message from the evaluation:" would be better? Any other idea?

> Indicate that expected output has punctuation/case removed

It's not always the case, it depends on the checker. Do you think saying "Output comparison may ignore punctuation and case." would be fine?

I'm putting the rest of the wording changes, thanks for that!
