### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#43]
We don't understand why "evaluation answered" appears at this stage. Where can we change this parameter?
![image](https://user-images.githubusercontent.com/19490273/41107962-c9897bb6-6a49-11e8-86d1-5299891a9f68.png)

**Comment by mblockelet** [comment]
Hi, "evaluation answered" appears because your checker for this tasks displayed a messge. It's the title for the box below.

**Comment by EllaHa** [comment]
Hi Michel, thanks for this update. Could we eventually write "feedback" instead of "evaluation answered"?
