### ISSUE TITLE
Change/hide file language

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#46]
In the submission tab,
File language : can we turn it off using the Theme ? 
If no should be renamed to Programming Language
![image](https://user-images.githubusercontent.com/19490273/44668137-db4f1780-aa1c-11e8-97cd-9438402f985d.png)

**Comment by mblockelet** [comment]
Hi,
It only appears if there are multiple `supportedLanguages`.

To put only one supported language :

- in the task-editor, change the key `supportedLanguages` to have only `c` in it, remove `*`
- if the task was created outside of the task-editor, edit the `index.html` file and change the key in the same way

and then reimport the task.
