### ISSUE TITLE
Wording for feedback

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#48]
Would it be possible to  change “Submission in c on ...” should be “Submitted on…” 
Change Submission for Submitted
Delete "in c"
![image](https://user-images.githubusercontent.com/19490273/44669506-56fe9380-aa20-11e8-8ea4-2fffd65a25f0.png)

**Comment by mblockelet** [comment]
Done!

**Comment by EllaHa** [comment]
Merci Michel, en revanche, cela apparait toujours comme sur le précédent screenshot exemple : https://lti.algorea.org/?taskUrl=https%3A%2F%2Ftasks.algorea.org%2Ftask.html%3FtaskId%3D134713993673150416&sLocale=en&theme=funtelecom) 
. 
![image](https://user-images.githubusercontent.com/19490273/44855362-22cae300-ac6b-11e8-9300-6205e52613e7.png)

**Comment by mblockelet** [comment]
Désolé, je n'avais pas bien précisé : il ne va cacher le langage que dans le cas où il n'y a qu'un seul langage activé pour la tâche, ce qui devrait être le cas bientôt pour toutes les tâches des MOOCs. J'ai aussi corrigé "Submission" en "Submitted", j'avais raté ça la première fois.

Par ailleurs, il est possible que ça ne se voie pas tout de suite à cause du cache.
