### ISSUE TITLE
Harmoniser les couleurs du theme fun telecom

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#49]
Would it be possible to have the same blue for buttons and lines?
![image](https://user-images.githubusercontent.com/19490273/44669627-aba20e80-aa20-11e8-9c85-1d4d52ea3ef3.png)

Ideally with this blue: 
HTML code: | #0075B3
-- | --
RGB code: | R: 0 G: 117 B: 179

**Comment by EllaHa** [comment]
Same for the green, would it be possible to change for blue? 
![image](https://user-images.githubusercontent.com/19490273/44669903-8eba0b00-aa21-11e8-93bc-6b6319f05603.png)

**Comment by EllaHa** [comment]
Same for the "request a hint" button

**Comment by mblockelet** [comment]
Done!
