### ISSUE TITLE
Cacher le bouton plein écran dans le thème FUN télécom

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#50]
Using LTI, we are not able to use taskgrader in full screen, which make useless the the full screen button. Would it be possible to hide this button in the theme? 
Thanks a lot
![image](https://user-images.githubusercontent.com/19490273/44670016-e2c4ef80-aa21-11e8-88f1-b86dff4f09df.png)

**Comment by mblockelet** [comment]
Done!
