### ISSUE TITLE
quizz taskgrader score

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#53]
it looks like there is a roundup or something happening ? more info here https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/567

**Comment by mblockelet** [comment]
It only happens when testing quiz, because defaults for a quiz are to remove points for wrong answers. It shouldn't happen when you integrate the quiz within LTI, as the default is not to remove points. Please tell me if it happens again, outside of testing.
