### ISSUE TITLE
Uploading image on quiz error

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#57]
<img width="1221" alt="Screenshot 2019-12-21 at 1 34 55 PM" src="https://user-images.githubusercontent.com/51734801/71305291-87c5c180-23f7-11ea-806c-0e629ec7de51.png">
As seen in the screenshot, an image needs to be attached in question 2 of quiz 'memory with linux' for the user to see. The image is uploaded correctly and is available in the images folder on task grader. However, when tested or connected to edX studio, the image is not seen. The edX link for this quiz is: https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020+type@vertical+block@dfeee47fa89b4a36840416ded731db0b
and taskgrader link is: http://task-editor.france-ioi.org/#edit/cspace%2F06%20Linux%20Basics%20The%20Command%20Line%20Interface%2FUnit%206.3%20C%20program%20compilation%20with%20gcc%2F02%20Managing%20memory%20with%20Linux%2F01_memory%20with%20linux

**Comment by mblockelet** [comment]
This bug is now fixed, and in particular the image you had the issue with has been fixed. If you have the issue again, please make sure to select the image and reselect the uploaded image you want to use.
