### ISSUE TITLE
quizz doesn't show up

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#58]
here is the screen capture:

MOOC 6 https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/courseware/fa3b199b4927423f90a0f80550b0d4c3/e241fa2b0ca1495db74ce4c94b47820d/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B1T2020%2Btype%40vertical%2Bblock%40267ce0dcde9041f49d7238686f5ffd7f 

![image](https://user-images.githubusercontent.com/8048877/72356849-41a80900-36ea-11ea-90d4-72a9c33e213e.png)

**Comment by remisharrock** [comment]
And happy new year @mathias-hiron  et @mblockelet  !!! :)

**Comment by mblockelet** [comment]
Happy new year @remisharrock ! This is an edX issue, and not on our side ; the edX LTI iframe was blocking before even reaching our servers. It seems the activity had not been Published, which might explain the issue ; however, at the moment it's also working by checking "hide from learners" in Studio. I assume the iframe blocks when it's not published.

I'll let you check the settings further!
