### ISSUE TITLE
Quiz fill-in the blanks

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#61]
One of the quizzes being made needs to use the fill in the blank feature of task grader, however, I am not sure how to make it recognise what the blank is. I tried “____” and some others but it does not recognise it. For reference it is for quiz:
cspace/05 C Programming Advanced Data Types/Unit 5.1 Structures/02 Access and modify structures/02_use the dot operator.
This is the link for the quiz: https://task-editor.france-ioi.org/#edit/cspace%2F05%20C%20Programming%20Advanced%20Data%20Types%2FUnit%205.1%20Structures%2F02%20Access%20and%20modify%20structures%2F02_use%20the%20dot%20operator

I have also attached a screenshot of the question.
<img width="1263" alt="Screenshot 2020-01-20 at 9 30 35 AM" src="https://user-images.githubusercontent.com/51734801/72734426-a38fc500-3b67-11ea-94b2-dbc2d57e691e.png">

**Comment by mblockelet** [comment]
Hello,

There was a button in the editor which was supposed to add gaps, but the button seems to have disappeared.

In the meanwhile, you can add gaps by switching to source code mode on the HTML editor, and inserting : `<span class="placeholder noneditable">&nbsp;</span>`. I'll look up why the button disappeared.

**Comment by AadhyaKocha** [comment]
That did solve the blanks issue. Thank you!
However, I'm not sure if this is related to this use but the grading for this quiz is showing the second part as incorrect. This may also be something to check.
<img width="1334" alt="Screenshot 2020-01-21 at 3 57 26 PM" src="https://user-images.githubusercontent.com/51734801/72842659-ce147780-3c66-11ea-8c56-c2f15890845b.png">

**Comment by mblockelet** [comment]
This last issue is now fixed too, it works now!
