### ISSUE TITLE
timeout while fetching resources from this file

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#62]
J'essaye de mettre à jour mais j'ai cette erreur:

Telecom/MOOC1/Week1/taskAfficherASCIIArt (rev 15115)
Status: Task import finished (no resources to send).

index.html: Timeout while fetching resources from this file.

merci pour l'aide !

**Comment by mblockelet** [comment]
Corrigé pour l'instant, un problème d'HTTPS. Il faut que je gère mieux ça quand j'aurai le temps.

**Comment by remisharrock** [comment]
j'ai toujours cette erreur aujourd'hui ?

**Comment by remisharrock** [comment]
https://github.com/remisharrock/cspace/01 C Programming Getting Started/Unit 1.1 Printing loops and comments/04 Printing text and new lines/02_print text over several lines/01 C Programming Getting Started/Unit 1.1 Printing loops and comments/04 Printing text and new lines/02_print text over several lines
Status: Task import finished (no resources to send).

index.html: Timeout while fetching resources from this file.

index_fa.html: Timeout while fetching resources from this file.

index_fr.html: Timeout while fetching resources from this file.

**Comment by mblockelet** [comment]
Est-ce que c'est bon maintenant ? J'ai réglé le problème de façon plus définitive.
