### ISSUE TITLE
File attaching error and importing error

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#64]
In cspace/07 C Programming Using Linux Tools and Libraries/Unit 7.4 Concluding the course/01 Final Project, while making the quiz I need to attach a file [stardata.txt](https://github.com/France-ioi/taskgrader/files/4112935/stardata.txt) that the student can see but I am not sure how to attach it as the files portion gives me only these options and does not read the file as far as I know. This is how I filled the blanks right now:
<img width="1034" alt="Screenshot 2020-01-25 at 4 58 40 PM" src="https://user-images.githubusercontent.com/51734801/73127838-717dc900-3f94-11ea-957d-7642513b9d4c.png">

Additionally, with or without the test file, this quiz when saved and imported is not producing an LTI link no matter changes I make to the quiz.
<img width="1256" alt="Screenshot 2020-01-25 at 4 56 33 PM" src="https://user-images.githubusercontent.com/51734801/73127852-a12cd100-3f94-11ea-8a22-db6addde750f.png">

**Comment by remisharrock** [comment]
I think it's connected to 
https://github.com/France-ioi/taskgrader/issues/62

**Comment by EllaHa** [comment]
same here
![image](https://user-images.githubusercontent.com/19490273/73287457-9757d780-41f9-11ea-9987-51629904b52b.png)

**Comment by mblockelet** [comment]
The import issue is connected to #62, but the file saving issue isn't. #62 should be fixed now, but I'll have to look into the file issue.

**Comment by mblockelet** [comment]
@AadhyaKocha The task editor has been updated, could you confirm that the extra files feature now works as you would expect?

**Comment by mblockelet** [comment]
(was fixed during meeting)
