### ISSUE TITLE
Compile-time error with code only occurs in Taskeditor

### ISSUE THREAD

**Issue by Eli-Boardman** [France-ioi/taskgrader#65]
On the final project for MOOC 4:

cspace/04 C Programming Pointers and Memory Management/Unit 4.4 Concluding the course/03 Final Project

When using the "test task" feature and submitting the provided solution as the user input, the following errors are displayed:

Résultat de la compilation :

592652565709606511.c: In function ‘main’:
592652565709606511.c:17:21: warning: ‘line’ is used uninitialized in this function [-Wuninitialized]
     int ** matrix = allocateIntStarArray(line);

However, the same code compiles and runs fine on my computer. It seems that "line" is indeed initialized prior to being used by the function, so it is unclear to me why this issue is occurring.

**Comment by mblockelet** [comment]
In the solution that you're talking, `int line` is declared but not initialized to any value. The warning the compiler is giving you is valid. You probably want to move the line `int ** matrix = allocateIntStarArray(line);` after the line `scanf("%d",&line);`.
