### ISSUE TITLE
couleurs et police pour les quizz

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#66]
relié à cette issue, peut-on essayer de ne pas avoir d'italique par défaut pour les question et du noir pour le texte au lieu du bleu ou du gris clair ? Pour tester.
Merci

https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/596

**Comment by mblockelet** [comment]
Bonsoir Rémi, on avait déjà prévu des modifications de design, que j'ai du coup mises en priorité. Voici à quoi ça ressemble maintenant :

![image](https://user-images.githubusercontent.com/11016337/74684471-e7f09e00-51c3-11ea-8c49-1da680eb7d6c.png)

Dis-moi ce que tu en penses, ces modifications ne sont pas en prod pour l'instant.

**Comment by remisharrock** [comment]
Ok je regarde avec l'équipe ça a l'air super !

**Comment by remisharrock** [comment]
Ok on valide ! Merci !

**Comment by mblockelet** [comment]
Bonjour, le nouveau style a été mis en place, il apparaîtra bientôt partout (question de cache) !
