### ISSUE TITLE
error 500 à vérifier

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#68]
j'ai l'impression que l'erreur 500 apparaît pour toutes les personnes la permière fois, pas seulement pour la première importation depuis task-editor ? 
![image](https://user-images.githubusercontent.com/8048877/75762645-4fb5f580-5d3b-11ea-9bc1-7444045bfeb6.png)

**Comment by mblockelet** [comment]
Salut,

Pour l'instant, mes tests d'aujourd'hui, et les logs, semblent indiquer que l'erreur ne se produit que la première fois que l'exercice est intégré. Les liens ont été changés récemment depuis les anciens liens lti.algorea.org vers les nouveaux liens imt.algorea.org, du coup il est possible que certains exercices viennent juste d'être chargés depuis imt.algorea.org pour la première fois lorsque tu es passé dessus.

Je continue à surveiller l'apparition de ces erreurs ; si elles se reproduisent souvent, j'essaierai de trouver une solution évitant cette erreur.

**Comment by remisharrock** [comment]
ok, merci de me tenir au courant, a priori pas de problème du côté des apprenants :)

**Comment by mblockelet** [comment]
J'ai vérifié encore cet après-midi et il n'y avait pas de nouveau problème ! Content que ça se passe bien du côté des apprenants aussi ! :)
