### ISSUE TITLE
ajout d'un test

### ISSUE THREAD

**Issue by eroux** [France-ioi/taskgrader#7]
Je pense que ce serait assez utile d'avoir un test et un petit script qui le lance, ça permettrait de savoir si la configuration de taskgrader est bonne... vu ce que ça fait quand elle ne l'est pas, je pense que ça vaut le coup. Qu'en penses-tu ?

**Comment by mblockelet** [comment]
Oui, en fait je suis en train de réorganiser le code de taskgrader avec des classes pour le rendre plus clair et mieux "découpé", du coup les tests suivront sous peu. Je te tiendrai au courant quand ce sera un peu plus prêt !

**Comment by eroux** [comment]
Ok super merci !

**Comment by eroux** [comment]
Je pense que ce serait pratique d'avoir un exemple fonctionnel d'utilisation de `genStdTaskJson.py` aussi, je ne sais pas trop sur quoi l'appeler, ce que ça me fait exactement, etc.
