### ISSUE TITLE
SQLSTATE[42000] [1203] User pixal already has more than 'max_user_connections' active connections

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#71]
Je ne sais pas si l'erreur vient des serveurs edx ou france ioi alors je mets une issue ici , merci !

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/courseware/9afb1233a3d74a62acc1625236e57a96/dfe4caf70cdd417b912948810b3393e7/?child=last

Le message d'erreur est celui-ci:

Erreur : SQLSTATE[42000] [1203] User pixal already has more than 'max_user_connections' active connections

Et le contenu du frame d'activité est hébergé à cette adresse:

https://imt.algorea.org/contents/5807-5802-1052234341352848159-456430099528178839-173916632910410154-13124066961705878-1059718547663225617/?sLocale=en

**Comment by mblockelet** [comment]
Salut, il y avait en effet un problème sur nos serveurs ce matin, mais le problème a été réglé !

**Comment by remisharrock** [comment]
merci !!
