### ISSUE TITLE
error message when infinite loop is not explicit

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#75]
here is the detail:
https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/641

**Comment by EllaHa** [comment]
Hi @mblockelet 
I hope this mail finds you weel. 
Another learner experimenting the same issue https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/discussion/forum/f915049c09f8c20c0da07a73954ad459c42d3243/threads/5ef8be6beac4b40850a19533 

Thanks you for your help in soliving this issue. 

All the best

**Comment by mblockelet** [comment]
Hello, answered on the issue linked above, it was a task configuration issue, on our side we already display timeouts.
