### ISSUE TITLE
Problem with quiz submission on all MOOCs (active session)

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#77]
Hi Michel, 

We are reaching out because learners are experimenting a significant issue. They are not able to submit quizzes anymore. 
Here is more https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/644

Could you please let us know if there is something we can do?

All the best, 

Ella

**Comment by mblockelet** [comment]
Fixed, commented on the linked bugreport.
