### ISSUE TITLE
Learner having problems loading taskgrader

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#79]
Hi Michel, 
Hope you are doing well. 
Here a learner is having issue with taskgrader, the page is not loading, if you have any clue on that, we would appreciate your help.
All the best, 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/course/threads/5f42557becdbe809c57d0f8f

**Comment by mblockelet** [comment]
Hello,
I hope you are doing well too.

Sadly, without more information, I cannot tell what was the issue, and I don't have debugging information on our side for issues that happened a month ago, as it is deleted after a couple of weeks. I didn't have other reports of the task platform not loading for other users, so it might have been an issue on that users' side.

Don't hesitate to reopen the issue if this happens again!
