### ISSUE TITLE
taskgrader : behavior of the default checker ? 

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#80]
Michel may you check this issue ? Thanks !
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/discussion/forum/3da3e43f46a89465e3f22eca82dd420d3200ae0e/threads/5f47ce55d1eb0c0a87a6ca60

**Comment by remisharrock** [comment]
we also have to make sure that students didn't use that technique to pass all he tests for the all the tasks !

**Comment by rserranosmith** [comment]
I have isolated the issue, and it appears that if a user has an infinite loop with a `printf` statement inside of it, then it will pass the test. This method works for every activity in every MOOC. 
![Screen Shot 2020-09-17 at 10 57 16 AM](https://user-images.githubusercontent.com/49991645/93502940-aac4c980-f8d4-11ea-9da7-3f7de83ff88e.png)

**Comment by mblockelet** [comment]
Thank you for the bugreport, I found the issue and will implement a fix soon.

**Comment by mblockelet** [comment]
This is now fixed.

The issue was that when the program would output a large file full of newlines, checkers would start using too much memory and crash. The issue was present with a lot of checkers (not only the default one), so now taskgrader checks that the answer size is not too large compared to the expected answer and blocks otherwise.

**Comment by remisharrock** [comment]
Thank you Michel ! 
Do you think you can check if some students have used this issue through multiple tasks to pass all tasks ?

**Comment by mblockelet** [comment]
Hello, a quick check indicates that only a very low number of students may have used it. I can't easily have details on who, but it is very possible that it was just the student who discovered the issue, and then us trying to isolate the issue and reproduce it.
