### ISSUE TITLE
Problem with Safari

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#81]
Hi MIchel, 
hope this message finds you well. 
Some learners are encountering problem using taskgrader with Safari, here is the issue https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/646
Best, 
Ella

**Comment by mblockelet** [comment]
Hello Ella, I will answer on the linked bugreport.

**Comment by mblockelet** [comment]
Fixed and answered on the linked bugreport.
