### ISSUE TITLE
taskeditor: answers are not visible

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#85]
looks like on task-editor, the answers are not visible for questions with input text. for example
 cspace/06 Linux Basics The Command Line Interface/Unit 6.2 The Linux file system/01 Discovering the file system/01_discovering the file system 

on task-editor, where are the answers ? 

![image](https://user-images.githubusercontent.com/8048877/98984124-0ea8ee80-2522-11eb-928c-7afc50b4a6bc.png)

looks like this on edX:

![image](https://user-images.githubusercontent.com/8048877/98984053-f5a03d80-2521-11eb-98dd-9686f388f529.png)

**Comment by mblockelet** [comment]
This issue seems to be the source of #83 and #84 , thanks for the report, looking into why it's happening. The data is still there though, it's task-editor which seems to be the issue.

**Comment by mblockelet** [comment]
I should be fixed now, please tell me if you still encounter issues!
