### ISSUE TITLE
changing a regex expression with taskeditor ?

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#86]
How can we change this regex https://github.com/remisharrock/cspace/blob/639289dc9b3b9f474de12e52904eebf10bffb367/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.1%20Libraries%20in%20C/01%20Declaring%20and%20defining%20functions/01_function%20declaration%20versus%20definition/task_content_files/root.taskSettings.checker.checker.py#L301 

with task-editor ? 

We want indeed to allow any number of spaces between "ftoc" and the opening parenthesis "("

Thanks for the help !

**Comment by mblockelet** [comment]
I fixed it, it seems that a commit a year ago made task-editor lose the reference to the checker file. It was due to a bug a year ago which had been fixed since then.

If there are tasks which aren't letting you edit the checker, please tell me so I can look at them and fix them if needed.
