### ISSUE TITLE
multiple lines for conditions in C language

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#87]
So whenever there are multiple lines with conditions taskgrader do an infinite loop and they says there is no test : 

For example 
 if((tomorrow.month == 1 || tomorrow.month == 3 || tomorrow.month == 5 || tomorrow.month == 7 ||
    		tomorrow.month == 10) && tomorrow.day == 31) {

 does not work
but

 if((tomorrow.month == 1 || tomorrow.month == 3 || tomorrow.month == 5 || tomorrow.month == 7 || tomorrow.month == 10) && tomorrow.day == 31) {

works

more details here 
https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/653

**Comment by mblockelet** [comment]
Answered on the linked bugreport ; error from the task checked and not taskgrader.
