### ISSUE TITLE
not initializing a variable should make the task wrong

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#89]
the compiler should not initialize variable to 0, is it possible to turn that off ? 

more details here

https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/656

**Comment by mblockelet** [comment]
Answered on the linked bugreport : changed the message to "Results of your next submission will appear here." which is more neutral.

**Comment by mblockelet** [comment]
I don't know of any option preventing GCC from not zero-initializing, and looking around I only see people saying the same.

A solution would be to transform the unitialized warning into an error, what do you think about it?

**Comment by remisharrock** [comment]
yes, transforming warings to errors should do the trick ;)

**Comment by mblockelet** [comment]
I transformed that warning into an error. More info on the linked bugreport.
