### ISSUE TITLE
new lines in quizzes questions

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#93]
so I think it is related to #92 but not sure : 
new lines in questions like this :

![image](https://user-images.githubusercontent.com/8048877/102522917-2cc0bc00-4097-11eb-999d-5eb40f9cefce.png)

appear like that:

![image](https://user-images.githubusercontent.com/8048877/102523046-55e14c80-4097-11eb-817f-b068c7842cea.png)

thanks !

**Comment by mblockelet** [comment]
Fixed!
