### ISSUE TITLE
when multiple tests, if the last test fails, no feedback

### ISSUE THREAD

**Issue by remisharrock** [France-ioi/taskgrader#94]
it is related to:
https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/673

**Comment by remisharrock** [comment]
ping, any news ? Thank you !

**Comment by mblockelet** [comment]
Hello, this is not an issue with taskgrader, it's your checker for this task which has this behavior.

When testing quickly, it seems your checker just doesn't give any feedback if the solution output is empty, or something like that.
