### ISSUE TITLE
MOOC 7 final should Grader ignore comments 

### ISSUE THREAD

**Issue by AadhyaKocha** [France-ioi/taskgrader#97]
As seen in this [issue](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/687), the final quiz of MOOC 7 marks the students incorrect if they delete comments from the given code. I have made note not to do that in the question now but we were wondering if it is possible to change the grader to ignore comments when checking the code? Any thoughts on if this should be done? 
@remisharrock @EllaHa

**Comment by AadhyaKocha** [comment]
@mblockelet any ideas if comments can be ignored from the grader?

**Comment by mblockelet** [comment]
Hi, sorry I somehow missed this when you posted it the first time.

The grader can ignore comments if it wants ; but it is your own custom grader, it's not something the taskgrader can help with. You'll need to modify your own custom grader to do so.
