### ISSUE TITLE
Problem with fill in the blank

### ISSUE THREAD

**Issue by EllaHa** [France-ioi/taskgrader#99]
Hi Michel, 

For your info their was a problem with the fill in the blank activities. I seems that this type of activities was not working for a few hours this week. 

Best, 

https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/710

**Comment by mblockelet** [comment]
Hi, thanks for telling me. There was a small server issue but it recovered by itself. We're planning on making adjustments so that this kind of issue can be resolved faster.
